version: '3.9'
networks:
  symfony:

services:

  postgres:
    image: postgres:13-alpine
    container_name: database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=symfony
    tty: true
    ports: ["5432"]
    volumes:
      - ./postgres:/var/lib/postgres/data
    networks:
      - symfony

  webserver:
    container_name: php
    build:
      context: webserver
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./webserver/apache/sites-enabled/:/etc/apache2/sites-enabled/
      - ./webserver/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - symfony

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: wdiaz503@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin

    ports:
      - "8080:80"
    networks:
      - symfony
    restart: unless-stopped
